import HeaderLayout from '@/components/layouts/HeaderLayout'
import Link from 'next/link'
const CHALLENGES = [
  {
    name: 'Counter',
    path: './challenge/counter'
  },
  {
    name: 'Guess the number',
    path: './challenge/guess-the-number'
  },
  {
    name: 'Telephone Formatter',
    path: './challenge/telephone-formatter'
  }
]

export default function Home() {
  return (
    <>
      {/* <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/favicon.ico' />
      </Head> */}
      <HeaderLayout>Frontend Mini Challenges - Solutions by alexxtomas</HeaderLayout>
      <ul>
        {CHALLENGES.map(({ name, path }) => {
          return (
            <li key={name}>
              <Link href={path}>{name}</Link>
            </li>
          )
        })}
      </ul>
    </>
  )
}
